quant_config:
  algo: rtn
  model_type: "other_model"
  kwargs:
    w_dtype: int8    # select from ['int2', 'int3', 'int4', 'int8', 'float16']
    a_dtype: int8 # select from ['int2', 'int3', 'int4',  'int8', 'float16']
    device: 'cpu'
    offload: 'cpu'
    w_groupsize: -1
    a_groupsize: -1
    a_qtype: "per_token"              
    w_qtype: "per_channel"             
    w_has_zero: False
    a_has_zero: False
    w_unsign: False
    a_unsign: False
    quantization_type: 'dynamic'
    block_sequential: True
    layer_sequential: True
    skip_layers:                   # the linear layer to skip, should match the module name
      - lm_head
  calibrate_config:
    name: 'wikitext2'
    split: train
    nsamples: 1
    seqlen: 2048
  
  