quant_config:
  algo: rtn
  model_type: "llama"
  kwargs:
    w_dtype: int4    # select from ['int2', 'int3', 'int4', 'int8', 'float16']
    a_dtype: float16 # select from ['int2', 'int3', 'int4',  'int8', 'float16']
    device: 'cuda'
    offload: 'cpu'
    w_groupsize: -1
    a_groupsize: -1
    a_qtype: "per_tensor"              
    w_qtype: "per_channel"             
    w_has_zero: False
    a_has_zero: False
    w_unsign: True
    a_unsign: True
    quantization_type: 'static'
    block_sequential: False
    layer_sequential: False
    skip_layers:                   # the linear layer to skip, should match the module name
      - lm_head
  calibrate_config:
    name: 'wikitext2'
    split: train
    nsample: 1
    seqlen: 2048
  
  